### ISSUE TITLE
Support for Multiple pdf files

### ISSUE THREAD

**Issue by mandys** [codereverser/casparser#3]
Hi,

Do you have support for multiple pds files on your roadmap ?

For eg: I have 2 different reports - one from Karvy and other from Cams.

I can run the parser twice and see the results.

But, in the end I would like to see my complete portfolio in one place.

So, running 2 scripts with output on command line and then combining can be done away with it if the parser can support multiple pds.

I know each pdf can have a different password so that needs to be handled as well.

Or you want the parser to be agnostic to this and the person running the code should handle it at their end ?

Let me know.

Thanks!

**Comment by codereverser** [comment]
As far as I am aware, the CAS statements from CAMS or Karvy contains details of schemes registered across all three RTAs.

From [Karvy website](https://mfs.kfintech.com/investor/General/ConsolidatedAccountStatement)

> KFintech, CAMS and FTAMIL have come together to provide great convenience to investors by allowing them to see a consolidated view of their portfolio as a Mailback Statement.
If you have registered an email address in your folios across Funds serviced by CAMS, KFintech and FTAMIL, you can use this Mailback Service to obtain a consolidated PDF Account Statement at your registered email address


Also implementing this feature in the parser will be tricky due to various reasons 
1. handling separate passwords for pdfs 
2. identifying duplicate transactions
3. handling statements with different date ranges 

It may be better to leave it to the user to handle it by merging the two data structures. The logic for printing table is available in [casparser cli](https://github.com/codereverser/casparser/blob/main/casparser/cli.py)

**Comment by mandys** [comment]
Thanks @codereverser !

However, the use case gets interesting when your RMs or fund houses are using multiple emails on your behalf.

I have many friends, who have at least 2 emails on which their funds are listed.

Cams works on email and Karvy on PAN.

So, you see this feature could be useful to process your funds under multiple email accounts.

Also, I am assuming its a hobby project and you really don't need to handle all use cases 👍 

Can be handle in the code by individual developer.

p.s. Any plan on providing an html output ? The same table that we have on command line moved to html ?

**Comment by codereverser** [comment]
Hmm, yeah .. that makes sense. 

I am working on a webapp based on casparser, for this exact purpose i.e handling multiple portfolios of same person or family together, along with some meaningful statistics but have no ETA on that yet. 

Let me see if I can port some parts of the code from there to here; not sure about supporting multiple pdf files, but html output seems doable.
